---
####################################################
################ PHP Compatibility #################
######## Save the contents of this file as #########
## '.github/workflows/php-compatibility-8.2.yaml' ##
####################################################
name: PHP 8.2

on:
  push:
  pull_request:
    branches: [master, main]

permissions:
  contents: read

jobs:
  setup:
    name: Scan Code
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PHP Setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2-'
          ini-values: short_open_tag=On
          coverage: none

      - name: Run PHP Compatibility 8.2
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: '8.2-'
          # Specify directories to check
          paths: ${{ github.workspace }}/Plugin.php ${{ github.workspace }}/Controller/ ${{ github.workspace }}/Locale/ ${{ github.workspace }}/Helper/ ${{ github.workspace }}/Model/ ${{ github.workspace }}/Template/
